language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
jdk: oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew clean assembleDebug
