language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

jdk: oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew clean assembleDebug testDebugUnitTest
